events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Глобальный reverse proxy сервер на порту 80 хоста
    server {
        listen 80;
        server_name localhost;

        # 1. Корневой путь (/) проксируется на WordPress (порт 8081)
        location / {
            proxy_pass http://127.0.0.1:8081; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Путь /phpmyadmin/ проксируется на панель phpMyAdmin (порт 8082)
        location /phpmyadmin/ {
            # КРИТИЧЕСКИ ВАЖНО: Завершающий слэш на конце после 8082 обязателен!
            # Он заставляет Nginx отрезать кусок "/phpmyadmin/" из URL.
            # Контейнер phpMyAdmin получит чистый запрос к index.php, что предотвратит ошибку 404.
            proxy_pass http://127.0.0.1:8082/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 3. Требование 6: Путь /grafana проксируется на UI Grafana
        location /grafana/ {
            proxy_pass http://127.0.0.1:3000; # Перенаправляем на локальный порт Grafana
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
