global:
  scrape_interval: 1s     # Интервал сбора метрик (стандарт 5-15секунд)
  evaluation_interval: 1s

scrape_configs:
  # Метрики самого сервера Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Метрики железа и ОС хоста, собираемые node_exporter
  - job_name: 'Node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
