apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Сетевой адрес контейнера Prometheus внутри сети Docker
    isDefault: true              # Сделать этот источник данных дефолтным
    editable: true               # Разрешить редактирование через UI при необходимости
